#!/usr/bin/env python3
"""Initialize taskr worksheet headers and the small set of useful validations."""

from taskr.models.task import Priority, Status, TASK_COLUMNS
from taskr.storage.config import SheetsConfig
from taskr.storage.google_sheets import LOG_COLUMNS


def initialize() -> None:
    config = SheetsConfig.from_env()
    db, log = config.open_worksheets()
    db.update([list(TASK_COLUMNS)], range_name="A1:K1", value_input_option="RAW")
    log.update([list(LOG_COLUMNS)], range_name="A1:G1", value_input_option="RAW")
    columns = {name: index for index, name in enumerate(TASK_COLUMNS)}
    requests = []
    for name, values in (
        ("Priority", [str(int(value)) for value in Priority]),
        ("Status", [value.value for value in Status]),
    ):
        requests.append({
            "setDataValidation": {
                "range": {"sheetId": db.id, "startRowIndex": 1, "startColumnIndex": columns[name], "endColumnIndex": columns[name] + 1},
                "rule": {"condition": {"type": "ONE_OF_LIST", "values": [{"userEnteredValue": value} for value in values]}, "strict": True, "showCustomUi": True},
            }
        })
    # ID is generated by the application. Reject blanks without attempting to
    # duplicate UUID parsing in a spreadsheet formula.
    requests.append({
        "setDataValidation": {
            "range": {"sheetId": db.id, "startRowIndex": 1, "startColumnIndex": columns["ID"], "endColumnIndex": columns["ID"] + 1},
            "rule": {"condition": {"type": "TEXT_NOT_EQ", "values": [{"userEnteredValue": ""}]}, "strict": True},
        }
    })
    db.spreadsheet.batch_update({"requests": requests})


if __name__ == "__main__":
    initialize()

